plugins {
    id 'com.gradleup.shadow' version '9.2.2'
    id 'io.freefair.lombok' version '8.7.1'
    id "net.kyori.blossom" version "1.3.1"
    id 'java'
}

group = 'eu.xap3y'

def commandBase = "${permissionNode}|alias"
def mainCommand = "${permissionNode}"

def gitHash = {
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (Exception e) {
        return "unknown"
    }
}

blossom {
    replaceToken("@VERSION@", version)
    replaceToken("@GIT_HASH@", gitHash())
    replaceToken("@GIT_URL@", gitUrl)
    replaceToken("@PERMISSION_NODE@", permissionNode)
    replaceToken("@COMMAND_BASE@", commandBase)
    replaceToken("@MAIN_COMMAND@", mainCommand)
}

repositories {
    mavenCentral()
    //mavenLocal()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }

    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }

    maven {
        url = "https://jitpack.io"
    }

    /*maven {
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }*/
}

def usePapi = project.hasProperty("usePapi") && project.usePapi.toBoolean()
def useGui = project.hasProperty("useXaGui") && project.useXaGui.toBoolean()
def useStats = project.hasProperty("useBStats") && project.useBStats.toBoolean()
def useGson = project.hasProperty("useGson") && project.useGson.toBoolean()
def useVault = project.hasProperty("useVault") && project.useVault.toBoolean()
def useLuckPerms = project.hasProperty("useLuckPerms") && project.useLuckPerms.toBoolean()

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paperVersion ?: '1.21.10'}-R0.1-SNAPSHOT"
    implementation "org.incendo:cloud-annotations:${cloudAnnotationsVersion ?: '2.0.0'}"
    implementation "org.incendo:cloud-paper:${cloudPaperVersion ?: '2.0.0'}"


    if (usePapi) {
        compileOnly "me.clip:placeholderapi:${papiVersion ?: '2.11.6'}"
    }
    if (useGui) {
        implementation "eu.xap3y:xagui:${xaGuiVersion ?: '1.2-beta.4'}"
    }
    if (useStats) {
        implementation "org.bstats:bstats-bukkit:${bStatsVersion ?: '3.0.1'}"
    }
    if (useGson) {
        implementation "com.google.code.gson:gson:${gsonVersion ?: '2.10.1'}"
    }
    if (useVault) {
        compileOnly "net.milkbowl.vault:VaultAPI:${vaultVersion ?: '1.7'}"
    }
    if (useLuckPerms) {
        compileOnly "net.luckperms:api:${luckPermsVersion ?: '5.4'}"
    }

    /*
        OPTIONAL ( Dont forget to shadow them after enabling )
     */

    //implementation 'net.wesjd:anvilgui:1.10.1-SNAPSHOT'
    //implementation 'com.github.cryptomorin:XSeries:13.0.0'
    //implementation 'com.github.fierioziy.particlenativeapi:ParticleNativeAPI-core:4.4.0'

    // No need to shadow these:

    //implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.2'
    //compileOnly "de.tr7zw:item-nbt-api-plugin:2.14.1"
    //compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.10'
    //compileOnly 'com.github.TownyAdvanced:Towny:0.100.3.0'
    //compileOnly 'com.github.Slimefun:Slimefun4:RC-37'
    //compileOnly 'com.github.SkriptLang:Skript:2.9.2'
    //compileOnly 'org.apache.logging.log4j:log4j-core:2.23.1'
    //compileOnly 'com.github.TechFortress:GriefPrevention:16.18.4'
    //compileOnly 'org.spigotmc:plugin-annotations:1.2.3-SNAPSHOT'

    // JUnit and MockBukkit
    /*testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation 'com.github.seeseemelk:MockBukkit-v1.20:3.9.0'*/
}

def targetJavaVersion = javaVersion.toInteger() ?: 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [
            version: version,
            gitHash: gitHash(),
            permissionNode: permissionNode,
            commandBase: commandBase,
            mainCommand: mainCommand,
            baseCoordinates: baseCoordinates,
            mainClass: "${project.group}.${baseCoordinates.toLowerCase()}.${baseCoordinates}"
    ]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

build {
    dependsOn(shadowJar)
    //finalizedBy("copyToServer")
}

tasks.jar {
    enabled = false
}

tasks {
    shadowJar {
        archiveClassifier.set('')
        archiveBaseName.set(baseCoordinates)

        if (useStats) {
            relocate 'org.bstats', "${group}.${baseCoordinates.toLowerCase()}.util.bstats"
        }
        /*relocate 'com.github.fierioziy.particlenativeapi', "${group}.${baseCoordinates.toLowerCase()}.util.particlenativeapi"
        relocate 'com.cryptomorin.xseries', "${group}.${baseCoordinates.toLowerCase()}.util.xseries"
        relocate 'net.wesjd.anvilgui', "${group}.${baseCoordinates.toLowerCase()}.util.anvilgui"*/

        mergeServiceFiles()
        dependencies {
            exclude(dependency('io.papermc.paper:paper-api'))
        }
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
        exclude '**/module-info.class'
        exclude '**/*.kotlin_metadata', '**/*.kotlin_builtins'
        exclude 'META-INF/*.kotlin_module', 'META-INF/*.version', 'META-INF/versions/**'
        exclude '**/package-info.class'
        exclude 'META-INF/signatures/**'
        exclude '**/*Test*', '**/test/**', '**/tests/**', '**/*Example*', '**/samples/**', '**/javadoc/**'
        exclude '**/i18n/**', '**/locale/**', '**/locales/**', '**/messages/**'
    }
}

// Example task to upload the plugin to a server
// Also uncomment line 140 to enable it
/*tasks.register('copyToServer', Copy) {
    from shadowJar.archiveFile
    into "${layout.buildDirectory.get()}/../server/plugins"
}*/

//example file structure:
//root
//  - build.gradle
//  - src
//    - main
//      - java
//        - eu
//          - xap3y
//            - TemplateBukkitGradle
//              - TemplateBukkitGradle.java
//      - resources
//        - plugin.yml
//  - server
//    - plugins
//      - TemplateBukkitGradle.jar
