
baseCoordinates = "TemplateBukkitGradle"
version = 1.0

javaVersion = 21

permissionNode = 'example'

gitUrl = 'https://github.com/xap3y/templateBukkitGradle'

# Dependencies configs (ON/OFF)
useXaGui = false
useBStats = false
usePapi = false
useGson = false
useVault = false
useLuckPerms = false

# Dependency versions

paperVersion = '1.21.10'
xaGuiVersion = '1.2.1'
cloudAnnotationsVersion = '2.0.0'
cloudPaperVersion = '2.0.0-beta.13'
bStatsVersion = '3.0.1'
papiVersion = '2.12.6'
gsonVersion = '2.10.1'
vaultVersion = '1.7'
luckPermsVersion = '5.4'