name: TemplateBukkitGradle
version: '1.0'
main: eu.xap3y.templatebukkitgradle.TemplateBukkitGradle
api-version: '1.20'
authors: [ XAP3Y ]
description: template
website: https://xap3y.eu

#softdepend: [ PlaceholderAPI ]
#depend: [ NBTAPI, WorldGuard ]
#loadbefore: [OnePlugin, AnotherPlugin]

#load: POSTWORLD | STARTUP
#prefix: Example



